# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Planting Guide"
description: This is a blog about planting guides, tips and techniques on gardening and other planting articles. We believe that a happy life leads to happy living.

email: social@cleverberry.co.uk
website: https://cleverberry.co.uk
#blog logo
logo: "/assets/images/plantinguide_logo_v2.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Cleverberry'
author: 'Cleverberry'
author_image: "https://cleverberry.com/wp-content/uploads/2020/08/berrylogowhite.png"

paginate: 5

url: "" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: ''

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-176636207-3

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/cleverberry_
    desc: Follow me on twitter
    # share_url: https://twitter.com/cleverberry_
    # share_title: ?text=
    # share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/beberryclever
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

permalink: :title/