# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  
# Site settings
title: "Planting Guide"
description: This is a blog about planting guides, tips and techniques on gardening and other planting articles. We believe that a happy life leads to happy living.

email: social@cleverberry.co.uk
website: https://cleverberry.co.uk
#blog logo
logo: "/assets/images/plantinguide_logo_v2.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Cleverberry'
author: 'Cleverberry'
author_image: "https://cleverberry.com/wp-content/uploads/2020/08/berrylogowhite.png"

paginate: 5

url: "" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: ''

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-176636207-3

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/cleverberry_


  - icon: facebook
    url: https://www.facebook.com/beberryclever

  - icon: instagram
    url: http://instagram.com/cleverberry_

  - icon: linkedin
    url: https://www.linkedin.com/in/clever-berry-745a9a1b3/

  - icon: pinterest
    url: https://www.pinterest.ph/jl7139/

  - icon: tumblr
    url: https://cleverberry.tumblr.com/

permalink: :title/